#!/bin/sh
# gen-contributors.sh: regenerate CONTRIBUTORS.md from git history + blame.
#
# Usage:
#   ./scripts/gen-contributors.sh                  # print to stdout
#   ./scripts/gen-contributors.sh > CONTRIBUTORS.md
#
# Data sources:
#   * `git shortlog -sne --no-merges main`        per-author commit counts
#   * `scripts/compute-contributions.sh`           per-author blamed line %
#
# Deterministic and idempotent: given the same git history and same blame
# output the script emits identical bytes. POSIX sh, no bashisms.

set -eu

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

# Verify the support script exists. Without blame data we cannot fill the
# "Blame %" column, so fail loudly rather than silently emit zeros.
if [ ! -x scripts/compute-contributions.sh ]; then
    echo "scripts/compute-contributions.sh not found or not executable" >&2
    exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

COMMITS_FILE="$TMP_DIR/commits"
BLAME_FILE="$TMP_DIR/blame"
JOINED_FILE="$TMP_DIR/joined"

# --- commits -----------------------------------------------------------------
#
# `git shortlog -sne --no-merges main` output format is:
#     <leading spaces><count>\t<Name> <<email>>
# Strip the leading whitespace and split into <count>\t<name>\t<email>.
git shortlog -sne --no-merges main \
    | awk '
        {
            # Trim leading spaces produced by shortlog right-aligned counts.
            sub(/^[[:space:]]+/, "");
            # Split off the count from the rest of the line.
            count = $1;
            sub(/^[0-9]+[[:space:]]+/, "");
            # The remainder is "<Name> <email>"; extract email between <>.
            line = $0;
            email = line;
            sub(/^.*</, "", email);
            sub(/>.*$/, "", email);
            name = line;
            sub(/[[:space:]]*<[^>]*>[[:space:]]*$/, "", name);
            printf("%s\t%s\t%s\n", count, name, email);
        }
    ' > "$COMMITS_FILE"

# --- blame -------------------------------------------------------------------
#
# Run the existing line-blame script, then read the PER_AUTHOR-style table it
# writes inline. compute-contributions.sh prints "Wrote ..." messages but the
# numbers we need live in .github/badges/contributions.md.  Rather than parse
# that markdown, recompute from a fresh blame pass so the two scripts stay
# independent. Output rows: <pct>\t<email>.
#
# We re-derive the same totals here using the same find-set so that any future
# tweak to compute-contributions.sh's file list flows through unchanged.
{
    find src include bench -type f \
        \( -name '*.cpp' -o -name '*.hpp' -o -name '*.h' \) 2>/dev/null
    [ -f coremetrics.cpp ] && echo coremetrics.cpp
} > "$TMP_DIR/files"

if [ ! -s "$TMP_DIR/files" ]; then
    echo "no source files found for blame pass" >&2
    exit 1
fi

# Per-line author-mail dump, identical strategy to compute-contributions.sh.
while IFS= read -r f; do
    [ -n "$f" ] || continue
    git blame -w -C -M --line-porcelain -- "$f" 2>/dev/null \
        | awk '
            /^author-mail / {
                mail = $0;
                sub(/^author-mail </, "", mail);
                sub(/>$/, "", mail);
                print mail;
            }
        '
done < "$TMP_DIR/files" > "$TMP_DIR/blame_raw"

TOTAL_LINES=$(wc -l < "$TMP_DIR/blame_raw" | awk '{print $1}')
if [ "$TOTAL_LINES" -eq 0 ]; then
    echo "blame produced 0 lines" >&2
    exit 1
fi

# Aggregate to <count>\t<email>, then to <pct>\t<email>.
awk '{ c[$0]++ } END { for (m in c) printf("%d\t%s\n", c[m], m) }' \
    "$TMP_DIR/blame_raw" \
    | awk -F'\t' -v t="$TOTAL_LINES" '
        { printf("%.1f\t%s\n", ($1 / t) * 100, $2) }
    ' > "$BLAME_FILE"

# --- join commits + blame on email ------------------------------------------
#
# For every commits row, look up the email in the blame file. Missing entries
# render as "0.0%" so authors with only docs/test commits still appear.
awk -F'\t' '
    NR == FNR { pct[$2] = $1; next }
    {
        email = $3;
        share = pct[email];
        if (share == "") share = "0.0";
        # Re-key on count descending, then name for tie-stability.
        printf("%s\t%s\t%s\t%s\n", $1, $2, email, share);
    }
' "$BLAME_FILE" "$COMMITS_FILE" \
    | sort -t "$(printf '\t')" -k1,1nr -k2,2 > "$JOINED_FILE"

# --- emit CONTRIBUTORS.md ----------------------------------------------------

{
    echo '# Contributors'
    echo
    echo 'This file is auto-generated by `scripts/gen-contributors.sh` on every push to main.'
    echo
    echo '| Name | Email | Commits | Blame % |'
    echo '|------|-------|---------|---------|'
    while IFS="$(printf '\t')" read -r count name email share; do
        [ -n "$count" ] || continue
        printf '| %s | %s | %s | %s%% |\n' "$name" "$email" "$count" "$share"
    done < "$JOINED_FILE"
}
