name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: SDL3 Dependencies
      uses: libsdl-org/setup-sdl@main
      id: sdl3
      with:
        install-linux-dependencies: true
        version: 3-latest
        version-sdl-ttf: 3-latest
    - name: Build and Test
      run: |
        export SDL_VIDEO_DRIVER=dummy
        export LD_LIBRARY_PATH=${SDL3_ROOT}/lib:$LD_LIBRARY_PATH
        make CXXFLAGS="-std=c++23 -Wall -I ./include $(pkg-config --cflags sdl3)" LDFLAGS="$(pkg-config --libs sdl3)" test